### ISSUE TITLE
Unit tests fail on M1 Mac

### ISSUE THREAD

**Issue by odoublewen** [alexlancaster/pypop#147] opened 2023-10-18 20:55 UTC
**Describe the bug**
Several unit tests fail, with apparent numerical differences.  Please see attachments:
* pytest console output: [pypop-pytest.txt](https://github.com/alexlancaster/pypop/files/13033899/pypop-pytest.txt)
* pytest file output: [pytest_run_test.tar.gz](https://github.com/alexlancaster/pypop/files/13033904/pytest_run_test.tar.gz)

**Environment**
Hardware: Apple M1 Pro
OS: MacOS 12.6.7
Version: pypop 1.0.0b3

**Additional context**
This is using the beta release referred to in https://github.com/alexlancaster/pypop/issues/142

**Comment by alexlancaster** [comment] 2023-10-18 21:05
Thanks for the report!  In 612d385455eb4c736bde0fd2eb341761f6cd2f1d I added a note on the website, stating that M1/arm64 are not yet ready for production due to these pretty sizeable numerical differences.  (cc @rsingle )

**Comment by alexlancaster** [comment] 2023-10-18 21:08
I'm marking this as the milestone "Nice-To-Have" because I don't think this should hold up the 1.0.0 release.

**Comment by alexlancaster** [comment] 2023-10-23 23:27
@odoublewen , @rsingle: following Rich's intuition about `calloc()` I realized we were missing corresponding `free()` statements for some LD arrays that might fix the arm64 issue.  I've commited a fix, but needs testing on arm64.  

The builds are available through the CI system for the branch, this specific build is here:

https://github.com/alexlancaster/pypop/actions/runs/6620167664

if you scroll down, you'll see the file `artifact.zip`, which should contain a single arm64 wheel download it, then:

```
unzip artifact.zip
pip install pypop_genomics.... (i.e. name of the wheel file)
```

the attempt to re-run the unit tests.  (Note that you need to be logged into github to see the `artifact.zip` link on the website).

**Comment by odoublewen** [comment] 2023-10-24 01:24
Ok, did all of the above, but unfortunately, the unittests appear to fail for exactly the same reasons.  The results look identical to the failed results that I posted above.  And just to confirm that I have installed the build you instructed me to install:
```
$ pypop --version
pypop 1.0.0b5.post4+g47091df
```
...which looks like the right commit.

**Comment by alexlancaster** [comment] 2023-10-24 01:42
> Ok, did all of the above, but unfortunately, the unittests appear to fail for exactly the same reasons. The results look identical to the failed results that I posted above. And just to confirm that I have installed the build you instructed me to install:
> 
> ```
> $ pypop --version
> pypop 1.0.0b5.post4+g47091df
> ```
> 
> ...which looks like the right commit.

Hmm, bummer.  I was 70% certain that would possibly fix it.  I guess it's something else.  Doing another investigation of the code now and I'll post links to update builds when I get them.

**Comment by odoublewen** [comment] 2023-10-24 01:56
Would it be interesting to know whether it works on an ARM-based linux box?

I have Debian on a Raspberry pi...

**Comment by alexlancaster** [comment] 2023-10-24 02:06
> Would it be interesting to know whether it works on an ARM-based linux box?
> 
> I have Debian on a Raspberry pi...

yes, most definitely.  although I'm not sure if we have arm64 linux builds enabled or not.  let me check.

**Comment by alexlancaster** [comment] 2023-10-24 02:59
@odoublewen I'm pushing a new build that will be available here:

https://github.com/alexlancaster/pypop/actions/runs/6621761999

download the new wheel as before.  but just run a single unit test (by supplying a `-k` option to run just one function):
```
pytest -v -k test_USAFEL_slatkin_guothompson_emhaplofreq tests
```

This should generate a single directory.  I'm interested in the XML output and the console output.

**Comment by alexlancaster** [comment] 2023-10-24 03:04
> @odoublewen I'm pushing a new debugging build that will be available here:
> 
> https://github.com/alexlancaster/pypop/actions/runs/6621761999
> 

oops,  sorry that build had a typo, try this one:

https://github.com/alexlancaster/pypop/actions/runs/6621796269

**Comment by odoublewen** [comment] 2023-10-24 15:49
Here you are:
* [pypop pytest console.txt](https://github.com/alexlancaster/pypop/files/13120375/pypop.pytest.console.txt)
* [run_test_USAFEL_slatkin_guothompson_emhaplofreq_rhwzri5b.zip](https://github.com/alexlancaster/pypop/files/13120392/run_test_USAFEL_slatkin_guothompson_emhaplofreq_rhwzri5b.zip)

**Comment by alexlancaster** [comment] 2023-10-24 22:50
Thanks @odoublewen!  That's really helpful.  No we're geting somewhere. I haven't located the ultimate error, but getting closer.  It looks like one of the proximal reasons the numbers are out is that the `dij` values aren't being computed properly, even though the maximum likelihood (the `mle` below) is fine. This is because the coordinates given to it are all zeros (see the diff in the outputs below, red is the original, correct output , the green is the incorrect arm64 output).  I'm spinning yet another build that debugs the data structure `haplocus` that feeds into this.  @rsingle may want to take a look 

```diff
 ***
 dij[0, 0, 0]=0, mle[0]=0.125
-dij[0, 1, 0]=0, mle[1]=0.125
-dij[0, 2, 0]=0, mle[2]=0.0625
-dij[0, 3, 0]=0, mle[3]=0.0625
-dij[0, 4, 0]=0, mle[4]=0.25
-dij[0, 5, 0]=0, mle[5]=0.125
-dij[0, 6, 0]=0, mle[6]=0.1875
-dij[0, 7, 0]=0, mle[7]=0.0625
+dij[0, 0, 0]=0.125, mle[1]=0.125
+dij[0, 0, 0]=0.25, mle[2]=0.0625
+dij[0, 0, 0]=0.3125, mle[3]=0.0625
+dij[0, 0, 0]=0.375, mle[4]=0.25
+dij[0, 0, 0]=0.625, mle[5]=0.125
+dij[0, 0, 0]=0.75, mle[6]=0.1875
+dij[0, 0, 0]=0.9375, mle[7]=0.0625
 ***
 dij[0, 0, 0]=0, mle[0]=0.222222
```

**Comment by alexlancaster** [comment] 2023-10-24 22:51
@odoublewen  new build: https://github.com/alexlancaster/pypop/actions/runs/6633354084

**Comment by odoublewen** [comment] 2023-10-24 23:07
Here you go
[pytest_console.txt](https://github.com/alexlancaster/pypop/files/13131194/pytest_console.txt)
[run_test_USAFEL_slatkin_guothompson_emhaplofreq_null4jvy.zip](https://github.com/alexlancaster/pypop/files/13131234/run_test_USAFEL_slatkin_guothompson_emhaplofreq_null4jvy.zip)

**Comment by alexlancaster** [comment] 2023-10-25 00:16
> Here you go [pytest_console.txt](https://github.com/alexlancaster/pypop/files/13131194/pytest_console.txt) [run_test_USAFEL_slatkin_guothompson_emhaplofreq_null4jvy.zip](https://github.com/alexlancaster/pypop/files/13131234/run_test_USAFEL_slatkin_guothompson_emhaplofreq_null4jvy.zip)

Thanks - getting even closer!  It looks like parts of `count_unique_haplos()` function aren't even being called, because there should be debug statements that start with `inside count_unique_haplos: `.  new builds will be on their way soon!

**Comment by alexlancaster** [comment] 2023-10-25 01:43
new build: https://github.com/alexlancaster/pypop/actions/runs/6634653670

**Comment by odoublewen** [comment] 2023-10-25 16:09
[run_test_USAFEL_slatkin_guothompson_emhaplofreq_2gsdc7vt.tar.gz](https://github.com/alexlancaster/pypop/files/13168180/run_test_USAFEL_slatkin_guothompson_emhaplofreq_2gsdc7vt.tar.gz)
[Terminal Saved Output.txt](https://github.com/alexlancaster/pypop/files/13168181/Terminal.Saved.Output.txt)

What I was thinking when I asked you about arm-linux is: if we could get the same test failure on an arm-based linux machine, then maybe it would be possible to run your unit tests in CI and debug that way.  I suppose it's probably hard to find real M1 mac CI runners (without paying a premium for the privilege of Apple) but seems like arm-linux shouldn't be hard to come by, these days.

**Comment by alexlancaster** [comment] 2023-10-25 20:12
> [run_test_USAFEL_slatkin_guothompson_emhaplofreq_2gsdc7vt.tar.gz](https://github.com/alexlancaster/pypop/files/13168180/run_test_USAFEL_slatkin_guothompson_emhaplofreq_2gsdc7vt.tar.gz) [Terminal Saved Output.txt](https://github.com/alexlancaster/pypop/files/13168181/Terminal.Saved.Output.txt)

Thanks - that's useful.  I'm pretty sure I've zeroed in on the bit of problematic code, it's in this section:

https://github.com/alexlancaster/pypop/blob/871de9ae9025b66328b6f0e2b79074f714baf3ba/src/emhaplofreq/emhaplofreq.c#L1233-L1239

in your output, it's executing the `else` part of the statement:
```
inside count_unique_haplos: l=0, m=0, temp_array=02:10~~, unique_allele=02:10~
```
whereas on my Linux machine, where it passes the tests, it shows it's executing (correctly) the `if` part of the statement:
```
inside count_unique_haplos: haplocus[0][0]=0, temp_array=02:10~, unique_allele=02:10~
```

If `temp_array` and `unique_allele` are the same, it should be doing the `if` part - instead it's executing the `else` part.  So there must be some issue with the behaviour of the `strcmp()` function on arm64.
 
> What I was thinking when I asked you about arm-linux is: if we could get the same test failure on an arm-based linux machine, then maybe it would be possible to run your unit tests in CI and debug that way. I suppose it's probably hard to find real M1 mac CI runners (without paying a premium for the privilege of Apple) but seems like arm-linux shouldn't be hard to come by, these days.

Yeah - I can look into whether any true arm64-linux runners are available via GitHub Actions. I don't think so, but there may be a way. 

> I certainly don't mind doing these tests, but as CI systems go, I am on the slow end!

No worries.  I think we're relatively close to getting an answer on this particular issue, but it would be good to have the option to run them on a true arm64 machine for future issues - at least that way we can have the unit tests run on an arm64 platform (currently they are always skipped on macos).

**Comment by alexlancaster** [comment] 2023-10-25 20:23
As noted here: https://stackoverflow.com/a/68702051 

```
if (!strcmp(s1, s2))
```
is not a great idiom, because it suggests that you're doing something if the strings are **different**, whereas, in fact, the `if` statement is executed when they are the **same**.  This down the fact that the exit code from `strcmp` is zero when `s1 = s2` but you have to invert it (using `!`) to get the `if` statement to execute.  Yeah - it's like a double negative. Looking at how arm64 handles the exit codes now.

**Comment by rsingle** [comment] 2023-10-25 20:38
The [Terminal Saved Output.txt](https://github.com/alexlancaster/pypop/files/13168181/Terminal.Saved.Output.txt) file shows that temp_array has 2 trailing ~s but unique_allele has only one.

OWEN'S OUTPUT
inside count_unique_haplos: l=0, m=0, temp_array=02:10~~, unique_allele=02:10~

ALEX'S OUTPUT
inside count_unique_haplos: haplocus[0][0]=0, temp_array=02:10~, unique_allele=02:10~

**Comment by alexlancaster** [comment] 2023-10-25 20:52
You can see from the same Terminal Saved Output from Owen, that the extra `~` is added in the temporary array:

```
haplo_ar[0]: 02:10~01:02~13:01~ temp_array[1]: 01:02~~ 
haplo_ar[0]: 02:10~01:02~13:01~ temp_array[2]: 13:01~~ 
```
My output for the same section looks like this:
```
haplo_ar[0]: 03:07~13:01~ temp_array[0]: 03:07~ 
haplo_ar[0]: 03:07~13:01~ temp_array[1]: 13:01~ 
```

So I now think the error is in this section (I'm adding in more debugging statements there):

https://github.com/alexlancaster/pypop/blob/871de9ae9025b66328b6f0e2b79074f714baf3ba/src/emhaplofreq/emhaplofreq.c#L1202-L1217

**Comment by alexlancaster** [comment] 2023-10-25 21:27
@rsingle there's definitely wrong even further upstream, it seems to result from something happening to `GENOTYPE_SEPARATOR` when it's passed in from Python to the C extension,
```
in Python: GENOTYPE_SEPARATOR: ~
in Python: GENOTYPE_TERMINATOR: ~
start of main_proc: GENOTYPE_SEPARATOR=~~
start of main_proc: GENOTYPE_TERMINATOR=~
BEFORE count_unique_haplos: GENOTYPE_SEPARATOR=~~
BEFORE count_unique_haplos: GENOTYPE_TERMINATOR=~
INSIDE count_unique_haplos: GENOTYPE_SEPARATOR=~~
INSIDE count_unique_haplos: GENOTYPE_TERMINATOR=~
```

for some reason on the Linux (where unit tests pass), it gains an extra `~`, which actually accidentally "works" because the `strok()` consumes the extra `~`, whereas on arm64, it passes the string correctly, but breaks everything else downstream of it.  So need some more work here for sure.

**Comment by alexlancaster** [comment] 2023-10-25 21:30
OK, new build will be here: https://github.com/alexlancaster/pypop/actions/runs/6646361024 this should at least answer the question about what's being passed from Python to the SWIG-ed C extension and confirm or deny my hypothesis

**Comment by rsingle** [comment] 2023-10-25 23:39
> @rsingle there's definitely wrong even further upstream, it seems to result from something happening to `GENOTYPE_SEPARATOR` when it's passed in from Python to the C extension,
> 
> ```
> in Python: GENOTYPE_SEPARATOR: ~
> in Python: GENOTYPE_TERMINATOR: ~
> start of main_proc: GENOTYPE_SEPARATOR=~~
> start of main_proc: GENOTYPE_TERMINATOR=~
> BEFORE count_unique_haplos: GENOTYPE_SEPARATOR=~~
> BEFORE count_unique_haplos: GENOTYPE_TERMINATOR=~
> INSIDE count_unique_haplos: GENOTYPE_SEPARATOR=~~
> INSIDE count_unique_haplos: GENOTYPE_TERMINATOR=~
> ```
> 
> for some reason on the Linux (where unit tests pass), it gains an extra `~`, which actually accidentally "works" because the `strok()` consumes the extra `~`, whereas on arm64, it passes the string correctly, but breaks everything else downstream of it. So need some more work here for sure.

So is it that we are splitting the string into tokens based on the '~' delim and we have 2 '~'s in a row that is handled differently on M1?
The lines in the terminal output: 
  in Python: GENOTYPE_SEPARATOR: ~
  in Python: GENOTYPE_TERMINATOR: ~
     start of main_proc: GENOTYPE_SEPARATOR=~
     start of main_proc: GENOTYPE_TERMINATOR=~~
don't make sense to me (just the last one).  They should all be a single ~ like they are in the standalone emhaplofreq. It looks like they are not being passed correctly somehow.

**Comment by alexlancaster** [comment] 2023-10-25 23:51
> So is it that we are splitting the string into tokens based on the '~' delim and we have 2 '~'s in a row that is handled differently on M1? The lines in the terminal output: 
> ```
> in Python: GENOTYPE_SEPARATOR: ~ 
> in Python: GENOTYPE_TERMINATOR: ~ 
> start of main_proc: GENOTYPE_SEPARATOR=~ 
> start of main_proc: GENOTYPE_TERMINATOR=~~ 
> ```
> don't make sense to me (just the last one). They should all be a single ~ like they are in the standalone emhaplofreq. It looks like they are not being passed correctly somehow.

I think what's happened is that there's a latent bug in how the `GENOTYPE_` variable is passed from Python to the C program, and that it was masked by the behaviour of the strok splitting that luckily "just worked" on all other architectures - and that arm64 somehow is exposing it.  It's puzzling but I'm sure they'll be an answer. The good news is that we can drill down into this locally before going back to M1 builds.

**Comment by alexlancaster** [comment] 2023-10-26 01:45
OK, I was able to fix it in Linux, so now we only see a single separator `~` in the debug output, see below, no duplicates

```
in Python: GENOTYPE_SEPARATOR: ~
in Python: GENOTYPE_TERMINATOR: ~
start of main_proc: GENOTYPE_SEPARATOR=~
start of main_proc: GENOTYPE_TERMINATOR=~
BEFORE count_unique_haplos: GENOTYPE_SEPARATOR=~
BEFORE count_unique_haplos: GENOTYPE_TERMINATOR=~
INSIDE count_unique_haplos: GENOTYPE_SEPARATOR=~
INSIDE count_unique_haplos: GENOTYPE_TERMINATOR=~
```

Here was an issue with the SWIG typemap passing in a character string. I think I've fixed this.  Now the output looks like this, and the unit tests still pass.  I'm hoping this will also fix it on arm64:

https://github.com/alexlancaster/pypop/actions/runs/6648346541

If the specific unit test passes we've been focusing on passes, try again on the full unit test suite.

**Comment by alexlancaster** [comment] 2023-10-26 01:59
@odoublewen re the arm for Linux idea, it looks like there's an option here to use github actions with an external hosted arm64 for Linux runner: https://buildjet.com/for-github-actions  you can get a bunch of free minutes.  I might try and set that up if I have time.

**Comment by alexlancaster** [comment] 2023-10-26 05:27
> @odoublewen re the arm for Linux idea, it looks like there's an option here to use github actions with an external hosted arm64 for Linux runner: https://buildjet.com/for-github-actions you can get a bunch of free minutes. I might try and set that up if I have time.

I was able to  use setup `buildjet` with a separate GitHub Action to create ARM64 wheels on Linux,  here: https://github.com/alexlancaster/pypop/actions/runs/6649730429/job/18068728816  and they now pass unit tests!  buildjet has a a certain number of minutes allowed on the free tier, which is enough to test the odd build.

These obviously won't install on MacOS X/M1, but assuming the original issue is ARM-specific only, and not also something Apple Silicon-specific, this should bode well for the M1/ARM64 builds.

**Comment by odoublewen** [comment] 2023-10-26 15:35
All tests pass now!  🎉   61773eae6d2b2951b8d0eb063e8e309d3fcf2980 was a good catch!

I'm a bit confused about how/why this would be specific to M1.  Perhaps M1 is a red herring, perhaps there something else different in my environment (like the version of swig, etc.)  It'd be interesting to push a previous commit through to your arm/linux buildjet tester, to see if it fails the same way I was seeing.

**Comment by alexlancaster** [comment] 2023-10-26 19:13
> All tests pass now! 🎉 [61773ea](https://github.com/alexlancaster/pypop/commit/61773eae6d2b2951b8d0eb063e8e309d3fcf2980) was a good catch!

Hooray!
 
> I'm a bit confused about how/why this would be specific to M1. Perhaps M1 is a red herring, perhaps there something else different in my environment (like the version of swig, etc.) It'd be interesting to push a previous commit through to your arm/linux buildjet tester, to see if it fails the same way I was seeing.

Good idea - I'll try and revert https://github.com/alexlancaster/pypop/commit/61773eae6d2b2951b8d0eb063e8e309d3fcf2980 and see if the issues crops up on arm64/Linux.  I suspect it's a combination of that particular architecture and compiler (gcc) and not Apple Silicon M1 per se.

**Comment by alexlancaster** [comment] 2023-10-26 19:34
OK, the build failed on ARM64 with the revert: https://github.com/alexlancaster/pypop/actions/runs/6658764149  for some reason I can't see the logs just yet.  either way, I'll create a PR to fix this and push to main

**Closed** 2023-10-27 03:13 UTC
Labels: bug

**Comment by alexlancaster** [comment] 2023-10-27 17:10
@odoublewen just to close the loop on this, I was able to reproduce the original error on arm64/Linux: https://github.com/alexlancaster/pypop/actions/runs/6670125317/job/18129367842#step:5:178

```
 Pairwise LD estimates
 ---------------------
 Locus pair            D      D'        Wn   ln(L_1)   ln(L_0)         S   ALD_1_2   ALD_2_1
-A:C             0.04309 1.20192   2.43975    -36.04    -50.35     28.61   2.49196   2.99098
-A:B                  NA      NA        NA    -26.51    -28.42      3.82        NA        NA
-C:B                  NA      NA        NA    -32.10    -21.53    -21.13        NA        NA
+A:C             0.02579 0.86447   0.78174    -36.04    -55.27     38.45   0.76174   0.75337
+A:B                  NA      NA        NA    -26.51    -26.51      0.00        NA        NA
+C:B                  NA      NA        NA    -32.10    -32.10      0.00        NA        NA
```
so it seems that is is arm64 specific.  I'm building a new pre-release: 1.0.0b7 to be pushed up to pypi.  When it's built, could you pip install it and run the unit tests once again?

**Comment by odoublewen** [comment] 2023-10-27 18:30
Installed `pypop_genomics-1.0.0b7-cp310-cp310-macosx_11_0_arm64.whl` from pypi, and successfully ran pytest on full test suite.

```
$ pytest 
====================================== test session starts ======================================
platform darwin -- Python 3.10.11, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/owensolberg/venv/data/pypop
collected 41 items                                                                              

tests/test_100k_Emhaplofreq.py s                                                          [  2%]
tests/test_AlleleColon.py ..                                                              [  7%]
tests/test_Filters.py ...                                                                 [ 14%]
tests/test_GenerateTSV.py .....                                                           [ 26%]
tests/test_GenotypeCommon.py ..                                                           [ 31%]
tests/test_Haplostats.py ......                                                           [ 46%]
tests/test_Popmeta.py ..                                                                  [ 51%]
tests/test_StringMatrix.py .............                                                  [ 82%]
tests/test_USAFEL.py ....                                                                 [ 92%]
tests/test_UserGuideExamples.py ..                                                        [ 97%]
tests/test_gthwe.py s                                                                     [100%]

=========================== 39 passed, 2 skipped in 63.46s (0:01:03) ============================

$ pypop --version
pypop 1.0.0b7
Copyright (C) 2003-2006 Regents of the University of California.
Copyright (C) 2007-2023 PyPop team.
This is free software.  There is NO warranty; not even for
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
