### ISSUE TITLE
Failing to run ./setup.py test

### ISSUE THREAD

**Issue by mqondisi** [alexlancaster/pypop#45] opened 2017-10-22 08:30 UTC
![image](https://user-images.githubusercontent.com/11156672/31859961-6cad62d4-b6e1-11e7-8dd8-f0b15c573a3c.png)

I gitcloned Pypop but still fail to run setup.py test to check if its correctly installed. I am generally a python novice please kindly point in the right direction

**Comment by sjmack** [comment] 2017-11-22 16:28
@mqondisi, the resolution of the screenshot you provided is too low to read.  Can you paste in some text that details your commands and any error messages you are getting?

**Comment by alexlancaster** [comment] 2023-02-13 23:17
> @sjmack Thanks you for the response. Please find attached my commands and errors encountered. I am running Red Hat® Enterprise Linux® Server (python 2.7.5). I basically can not install dependencies (pypop/DEV_NOTES.md), and additionally setup.py test gives errors. If possible, may you kindly guide me through the installation and optimization of Pypop and how (commands) to run my analysis. I seem to get lost following the instructions in https://github.com/alexlancaster/pypop
> 
> [Mqondisi_pypop installation and setup problems.txt](https://github.com/alexlancaster/pypop/files/1498676/Mqondisi_pypop.installation.and.setup.problems.txt)

Python 2 is now deprecated, the original instructions are now out-dated.  Your original build failed because you were trying to use `sudo` to install packages, but it seemed like you didn't have sudo permissions (this is typically needed on most Linux systems to install packages).

Please try following the new instructions in the README.md, by following the `miniconda` instructions. Using miniconda means you don't need to install any packages system-wide, so it skips the need to use `sudo`.

**Comment by alexlancaster** [comment] 2023-06-05 23:16
since this is a bug with obsolete Python 2 version, which are now obsoleted by coming v1.0.0 Python 3-based release (please visit https://github.com/alexlancaster/pypop#readme for instructions on how to build the v1.0.0 pre-release from source), I am going to close this bug as "not planned.

If you can reproduce this same bug with the newer version, please open-up a new bug.

**Closed** 2023-06-05 23:17 UTC
Labels: installation, obsolete
