### ISSUE TITLE
Locus mixup in haplotype returns in .tsv outputs

### ISSUE THREAD

**Issue by sjmack** [alexlancaster/pypop#22] opened 2017-07-13 17:07 UTC
The WS_BDCtrl_Test_EM.ini config file specifies `LociToEstHaplo=a:drb1:drb3`, and running  `./bin/pypop.py --generate-tsv -c WS_BDCtrl_Test_EM.ini BIGDAWG_SynthControl_Data.pop` generates the following in the *out.txt file: 

```
Haplotype frequency est. for loci: A:DRB1:DRB3
----------------------------------------------
Number of individuals: 1002 (before-filtering)
Number of individuals: 991 (after-filtering)
Unique phenotypes: 303
Unique genotypes: 907
Number of haplotypes: 618
Loglikelihood under linkage equilibrium [ln(L_0)]: -8090.394069
Loglikelihood obtained via the EM algorithm [ln(L_1)]: -7061.268470
Number of iterations before convergence: 267

Haplotypes sorted by frequency        
haplotype                                 frequency# copies
01:01:01:01~01:01:01~00:00                0.08110  160.7   
24:02:01:01~07:01:01:01~00:00             0.07921  157.0   
32:02~03:01:02~01:01:02:01                0.05701  113.0   
03:01:03~15:01:01:01~00:00                0.05449  108.0   
31:01:02:01~03:01:01:01~01:01:02:02       0.04338  86.0    

```

You can tell that the order of loci in the header matches the order of alleles in the haplotype, because there is no DRB1 or DRB3 24:02:01:01 allele, and because only DRB3, DRB4 or DRB5 should be noted as "absent" using 00:00. 

However, the loci in the haplotype in a different order in the 3-locus-haplotype.dat file: 

```
:pypop sjmack$ more 3-locus-haplo.dat 
pop     labcode method  ethnic  collect.site    region  latit   longit  complex locus   allele  allele.freq     allele.count
0       ****    ****    ****    ****    ****    ****    ****    ****    DRB3:A:DRB1     01:01:01:01~01:01:01~00:00      0.08110 160.7   
0       ****    ****    ****    ****    ****    ****    ****    ****    DRB3:A:DRB1     24:02:01:01~07:01:01:01~00:00   0.07921 157.0   
0       ****    ****    ****    ****    ****    ****    ****    ****    DRB3:A:DRB1     32:02~03:01:02~01:01:02:01      0.05701 113.0   
0       ****    ****    ****    ****    ****    ****    ****    ****    DRB3:A:DRB1     03:01:03~15:01:01:01~00:00      0.05449 108.0   
0       ****    ****    ****    ****    ****    ****    ****    ****    DRB3:A:DRB1     31:01:02:01~03:01:01:01~01:01:02:02     0.04338 86.0    
```

Similarly, the 3-locus-summary.dat file also has mis-ordered locus names:

```
:pypop sjmack$ more 3-locus-summary.dat 
n.gametes       locus1  locus2  locus3
0       ****    ****    ****    ****    ****    ****    ****    ****    1982    DRB3    A       DRB1    ****    
```

`./bin/popmeta.py --disable-ihwg BIGDAWG_SynthControl_Data-out.xml` generates the same locus-order problem but without the IHWG headers (which I now realize is why I wasn't using --generate-tsv in the pypop command line). 

```
:pypop sjmack$ more 3-locus-haplo.dat 
popname locus   allele  allele.freq     allele.count
0       DRB3:A:DRB1     01:01:01:01~01:01:01~00:00      0.08110 160.7   
0       DRB3:A:DRB1     24:02:01:01~07:01:01:01~00:00   0.07921 157.0   
0       DRB3:A:DRB1     32:02~03:01:02~01:01:02:01      0.05701 113.0   
0       DRB3:A:DRB1     03:01:03~15:01:01:01~00:00      0.05449 108.0   
0       DRB3:A:DRB1     31:01:02:01~03:01:01:01~01:01:02:02     0.04338 86.0  
```

```
:pypop sjmack$ more 3-locus-summary.dat 
n.gametes       locus1  locus2  locus3
0       1982    DRB3    A       DRB1    ****    
```

(Also, it looks like there are some extra fields in the 3-locus-summary.dat file. Not sure what that is about.)

The order of the loci listed in the .tsv files should match the order of the loci in the corresponding .ini file.  Someone who isn't paying close attention to the results would think that "DRB3:A:DRB1     24:02:01:01~07:01:01:01~00:00" means "DRB3*24:02:01:01~A*07:01:01:01~DRB1*00:00", and any system that is automatically assembling GL strings from these data would make the same mistake.

**Comment by sjmack** [comment] 2017-07-13 17:16
Also, the BIGDAWG_SynthControl_Data-out.xml file correctly identifies the order of loci, as specified in the .ini: 
```
<emhaplofreq>
<group mode="haplo" loci="A:DRB1:DRB3" showHaplo="yes">

```

I don't see anywhere else within <emhaplofreq>...<emhaplofreq> where the loci are identified or re-ordered. For example, in: 
```
<loci first="0" second="1">
<allelepair first="01:01:01:01~" second="01:01:01~">
```
and 
```
<loci first="0" second="2">
<allelepair first="01:01:01:01~" second="00:00~">
```

The allele at locus 0 corresponds to HLA A, the allele at locus 1 correspond to DRB1, and the allele at locus 2 corresponds to DRB3.

**Comment by sjmack** [comment] 2017-07-13 17:42
It looks like this may have been a problem with the 0.7.0 version of popmeta as well. I am looking at old data, and the locus transposition pattern may be different (loci 1 and 2 seem to be transposed instead of loci 0 and 2). I will have to dig a little deeper into this, and don't have time right now.

**Comment by alexlancaster** [comment] 2017-07-14 18:31
Good catch.  I'll look into it.  We should definitely add some tests for the .dat files to catch these things as well.

**Comment by alexlancaster** [comment] 2017-07-15 04:38
Could you add the .ini file to this issue? So I can reproduce, I didn't see the file in the other issues.

**Comment by sjmack** [comment] 2017-07-15 07:07
I uploaded the file (WS_BDCtrl_Test_EM.ini) in [this comment](https://github.com/alexlancaster/pypop/issues/4#issuecomment-313542730).

**Comment by alexlancaster** [comment] 2017-07-20 20:46
Hi @sjmack so it's just the locus labels that are wrong, not the actual order of the data they refer to right?

**Comment by alexlancaster** [comment] 2017-07-20 20:52
Hmm, so looking at the XSLT that does the transformation, it looks like at some point we wanted to ensure the loci appeared in map order:

https://github.com/alexlancaster/pypop/blob/master/xslt/meta-to-r.xsl#L921

map-order is defined here:

https://github.com/alexlancaster/pypop/blob/master/xslt/meta-to-r.xsl#L50

**Comment by sjmack** [comment] 2017-07-20 21:15
Well, the issue is that the order in which the loci are listed is not the same as the order in which the alleles at those loci are listed. So, it is fine to have the loci in map order, but the alleles should **also** be presented in map order -- otherwise you can't tell which alleles in the table correspond to which loci. 

in addition, PyPop's current map ordering of loci 
```
 <data:map-order>
  <locusname order="1">D6S2239</locusname>
  <locusname order="2">D6S2223</locusname>
  <locusname order="3">D6S2222</locusname>
  <locusname order="4">A</locusname>
  <locusname order="5">D6S265</locusname>
  <locusname order="6">C</locusname>
  <locusname order="7">B</locusname>
  <locusname order="8">MIB</locusname>
  <locusname order="9">TNFD</locusname>
  <locusname order="10">D6S273</locusname>
  <locusname order="11">DRA</locusname>
  <locusname order="12">DRB1</locusname>
  <locusname order="13">DQA1</locusname>
  <locusname order="14">DQIV</locusname>
  <locusname order="15">DQCARII</locusname>
  <locusname order="16">DQCAR</locusname>
  <locusname order="17">DQB1</locusname>
  <locusname order="18">G51152</locusname>
  <locusname order="19">DPA1</locusname>

  <locusname order="20">DPB1</locusname>
  <locusname order="21">D6S291</locusname>
 </data:map-order>
```
does not include the DRB3, DRB4, and DRB5 loci. This is probably why the A, DRB1 and DRB3 loci are listed as `DRB3:A:DRB1`.

So, the list of locusnames should be expanded, probably to include all of the loci listed [on this map](http://hla.alleles.org/inc/images/hla_map_1000.png), or in the [hla_nom.txt file](https://github.com/ANHIG/IMGTHLA/blob/Latest/wmda/hla_nom.txt), to be inclusive going forward. 

In addition, I'm not sure what the map order for DRB3, DRB4 and DRB5 is, since they are structural variants of each other, but they are all between the class I region and the DRB1 locus (see: [the MHC region in the GRC](https://www.ncbi.nlm.nih.gov/grc/human/regions/MHC) and [Andersson, 1998](http://www.bioscience.org/1998/v3/d/andersso/2.htm). So, it isn't clear how to order them. The convention is to list them after DRB1, but that breaks the map order rule.

**Comment by alexlancaster** [comment] 2017-07-20 21:21
That behaviour has been like that for a while, probably the first time it's been caught.  It may have been for whatever purposes the map order was forced, it wasn't necessary that the alleles had to also be in that order. My vague recollection is that it was done so the plots looked sensible.  But I agree with you, it should be consistent.

Maybe the simplest solution for the moment is to revert to the original order in the XML.  Not sure if that would break anything downstream for other applications that are relying on information in *.dat to be in map order.

**Comment by sjmack** [comment] 2017-07-20 21:23
That seems like a simple solution. Is "original order" the order in which the loci appear in the .pop file, or the order in which they are listed in the .ini for the [emhaplofreq] block?

**Comment by alexlancaster** [comment] 2017-07-20 21:29
I think the latter.

**Comment by sjmack** [comment] 2017-07-20 21:58
I think I have noticed this before, but only with the HLA-B and HLA-C locus, because map order C, B differs from alphabetical order B, C. I always assumed it was an import error my my part, and went back and fix it manually in the .dat files. Its nice to finally know that I wasn't making the same mistake over and over!

**Comment by alexlancaster** [comment] 2017-07-24 18:09
@sjmack: I've created an initial test harness for this.  Do a git pull and run:  

      py.test -s -v tests/test_GenerateTSV.py

Although currently it "passes" because I'm using the "old" (incorrect) output.  If you go into the subdirectory:  [```tests/data/output/```](https://github.com/alexlancaster/pypop/tree/master/tests/data/output), you'll find all the ```*.dat``` output files.  

I suggest that you modify those output files to have the alleles/loci names in the order you expect.  The test will initially fail.  Then I'll modify the code to make sure the test passes.  Having one person modify the expected output (in this case, you) and another person (in this case, me) do the implementation is a good way of making sure we're thinking about the problem in the same way (this a loose version of Test-Driven Development (TDD): https://en.wikipedia.org/wiki/Test-driven_development#Test-driven_development_cycle )

(Since I gave you access to the repo, you can modify those files directly either editing via the in-browser edit function or using ```git commit  <filename>``` and ```git push```, or adding them here).

**Comment by sjmack** [comment] 2017-07-25 06:06
So, the problem is that the test_GenerateTSV.py is calling the wrong .ini -- 
```
exit_code = base.run_pypop_process('./tests/data/WS_BDCtrl_Test_HW.ini', 
```

WS_BDCtrl_Test_HW.ini doesn't call [emhaplofreq], so it needs to be replaced with WS_BDCtrl_Test_EM.ini in test_GenerateTSV.py.

**Comment by sjmack** [comment] 2017-07-25 06:09
I should add, that there are .data files, and even 3-locus-* and 4-locus-* .dat files generated, but they contain only headers. I think it is a little odd that these .dat files (but not 2-locus-*.dat files!) are generated even when [emhaplofreq] is not called.

**Comment by alexlancaster** [comment] 2017-07-25 06:36
Fixed, try now.  On the extra files thing, file a separate issue for that too.

**Comment by sjmack** [comment] 2017-07-25 06:58
Okay. .dat files are successfully generated -- I make the changes and push them in the morning.

**Comment by sjmack** [comment] 2017-07-25 23:48
Here are the modified files, with .txt suffixes attached. 

[3-locus-haplo.dat.txt](https://github.com/alexlancaster/pypop/files/1175094/3-locus-haplo.dat.txt)
[3-locus-summary.dat.txt](https://github.com/alexlancaster/pypop/files/1175095/3-locus-summary.dat.txt)

**Comment by alexlancaster** [comment] 2023-06-07 06:25
committed a partial fix of this bug, by adding `DRB3` into the map order, as part of restoring `--generate-tsv` and `popmeta` functionality  (which had not yet been ported to Python 3 - required porting to a whole new XML/XSLT library as the libxml2 library is obsolete).  The work is being done on the `tsv_files` branch.

The unit test now _almost_ passes, some minor tweaking of the txt format is required, and the LLR is slightly off.

**Closed** 2023-06-09 17:24 UTC
Labels: bug
