### ISSUE TITLE
Problem with running 5locus haplotypefrequency using EMhaplofreq

### ISSUE THREAD

**Issue by vanihla5** [alexlancaster/pypop#49] opened 2018-02-09 06:15 UTC
When I was analyzing 5 loci Haplotype Frequencies for 1800 samples the following screen appeared 

But,I was able to analyze the same set of samples when I split them into 1400 and 400 . 

 
[screenshot of exe file.docx](https://github.com/alexlancaster/pypop/files/1709927/screenshot.of.exe.file.docx)

Please let me know the way to rectify the above problem.
with regards
Vani

**Comment by afadda91** [comment] 2018-09-05 04:57
hi Vani,
the limit for me was 1800 samples. it failed with 2000 and above. Did manage to sort out this problem?

**Comment by vanihla5** [comment] 2018-09-05 05:02
Thank you for your mail.
NO. I could not get results when the sample size was more than 1800.
If there is a way to resolve this, please let me know.

Dr S.Vani Ph.D
Assistant Director - HLA Laboratory
Jeenomics
*Jeevan Stem Cell Foundation*
22, Wheatcrofts Road, Nungambakkam
<https://maps.google.com/?q=22,+Wheatcrofts+Road,+Nungambakkam+Chennai-600034&entry=gmail&source=g>
Chennai-600034
<https://maps.google.com/?q=22,+Wheatcrofts+Road,+Nungambakkam+Chennai-600034&entry=gmail&source=g>

**Comment by alexlancaster** [comment] 2023-07-31 04:55
@vanihla5 : 0.7.0 is now obsolete and deprecated, so I'm going to close this bug. 

If can you still reproduce the same error with the recent pre-releases (installation instructions are here: http://pypop.org/docs/guide-chapter-install.html) then please open a new issue and include both the `.ini` and `.pop` file that causes the crash.  

my hunch is that you are running up against the memory limit for your computer.  emhaplofreq has some hard limits based on number of samples and number of loci, because the memory used scales exponentially.  the new haplo-stats module in the the newer pre-releases may help get around this.

**Closed by alexlancaster** 2023-07-31 04:55 UTC
Labels: bug, question, obsolete
